---
services:
  runner:
    build:
      context: .
      args:
        - PLATFORM=linux/amd64
    image: github-runner-linux
    restart: always
    platform: linux/amd64
    # Load environment variables from a file
    # env_file: '.env'
    # Env vars defined under environment will override those from the env_file
    environment:
      GIT_TOKEN: ${GIT_TOKEN}
      GIT_OWNER: ${GIT_OWNER}
      GIT_REPOSITORY: ${GIT_REPOSITORY}
      RUNNER_GROUP: ${RUNNER_GROUP}
      RUNNER_NAME: ${RUNNER_NAME}
      WORK_DIR: ${WORK_DIR}
      LABELS: ${LABELS}
      REUSE_EXISTING: true
    container_name: github-runner-linux
    working_dir: /home/docker
